version: "2.0"
services:

    kibana:
        image: kibana
        links:
            - elasticsearch
        environment:
            - ELASTICSEARCH_URL=http://elasticsearch:9200
        ports:
            - 80:5601

    elasticsearch:
        image: elasticsearch:alpine
        volumes:
            - elastic:/usr/share/elasticsearch/data
        ports:
          - 9200:9200

volumes:
  elastic:

